### ISSUE TITLE
New router support

### ISSUE THREAD

**Issue by fritek373** [routerkeygen/routerkeygen.github.io#3]
Last week some scientist found new vulnerabilities in some major routers! Here is the report: https://www.usenix.org/system/files/conference/woot15/woot15-paper-lorente.pdf. Is this the info you guys need to add it to the app? Or do you need some more specific details? Let me know what you think!

**Comment by fritek373** [comment]
Sorry, this shoudn't be posted here... :|

**Comment by ruiaraujo** [comment]
Yup, I am in contact with one of the guys behind the paper.

Thanks for alerting me.
